sudo: required

language: 
  - node_js

node_js:
  - "12.14.0"

services:
  - docker

stages:
  - Build

before_install:
  - yarn

jobs:
  include:
    - stage: "Build"
      name: "Build"
      script:
        - yarn build


deploy:
  provider: heroku
  api_key: $API_KEY
  app: api-tvfull


addons:
  apt:
    packages:
      - docker-ce