version: "3"

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - cluster.name=es-docker-cluster
    ports:
      - "9300:9300"
      - "9200:9200"
    networks:
      - api-backend
  
  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - "6379:6379"
    networks:
      - api-backend
  
networks:
  api-backend:
    external:
      name: api-backend

volumes:
  esdata: